owner: ergotopia-dev # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: ergotopia.fr
    url: https://www.ergotopia.fr
  - name: ergotopia.fr (blog)
    url: https://www.ergotopia.fr/blog
  - name: ergotopia.de
    url: https://www.ergotopia.de
  - name: ergotopia.de (blog)
    url: https://www.ergotopia.de/blog
  - name: ergotopia.de (API)
    url: https://api.ergotopia.de/check-status
  - name: ergotopia.de (plattform)
    url: https://plattform.ergotopia.de
  - name: ergotopia.de (plattform subdomain)
    url: https://ergotopia.partner.ergotopia.de
  - name: ergotopia.de (Pro X PDP)
    url: https://www.ergotopia.de/ergonomie-shop/hoehenverstellbarer-schreibtisch/desktopia-pro-x
  - name: ergotopia.de (NextBack PDP)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerostuhl/nextback-mit-kopfstuetze
  - name: ergotopia.de (One PDP)
    url: https://www.ergotopia.de/ergonomie-shop/hoehenverstellbarer-schreibtisch/desktopia-one
  - name: ergotopia.de (Masterback PDP)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerostuhl/masterback
  - name: ergotopia.de (PureBack PDP)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerostuhl/pureback
  - name: ergotopia.de (WellBack PDP)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerostuhl/wellback
  - name: ergotopia.de (Dyko PDP)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerohocker-stehhilfe/dyko
  - name: ergotopia.de (Tische Kat)
    url: https://www.ergotopia.de/ergonomie-shop/hoehenverstellbarer-schreibtisch
  - name: ergotopia.de (Stuhle Kat)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerostuhl

status-website:
  cname: status.ergotopia.de
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime monitor
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: "robots"
      content: "noindex"

status-page:
  robotsText: "User-agent: * \n Disallow: /"
  
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
