owner: ergotopia-dev # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: ergotopia.fr
    url: https://www.ergotopia.fr
  - name: ergotopia.fr (blog)
    url: https://www.ergotopia.fr/blog
  - name: ergotopia.de
    url: https://www.ergotopia.de
  - name: ergotopia.de (blog)
    url: https://www.ergotopia.de/blog
  - name: ergotopia.de (API)
    url: https://api.ergotopia.de/check-status
  - name: ergotopia.de (product: Desktopia Pro X)
    url: https://www.ergotopia.de/ergonomie-shop/hoehenverstellbarer-schreibtisch/desktopia-pro-elektrisch-memoryschalter
  - name: ergotopia.de (product: Masterback)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerostuhl/masterback
  - name: ergotopia.de (product: Nextback)
    url: https://www.ergotopia.de/ergonomie-shop/gesund-sitzen/ergonomischer-buerostuhl/nextback-mit-kopfstuetze
#  - name: partner.ergotopia.de
#    url: https://partner.ergotopia.de

status-website:
  cname: status.ergotopia.de
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime monitor
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: "robots"
      content: "noindex"

status-page:
  robotsText: "User-agent: * \n Disallow: /"
  
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
