owner: ergotopia-dev # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: ergotopia.de
    url: https://ergotopia.de

status-website:
  cname: status.ergotopia.de
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime monitor
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: "robots"
      content: "noindex"

status-page:
  robotsText: "User-agent: * \n Disallow: /"
  
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
